package org.tekfive.relaykt.tls

import java.nio.file.Files
import java.nio.file.Path
import java.security.KeyStore
import java.security.cert.X509Certificate
import javax.net.ssl.KeyManagerFactory
import javax.net.ssl.SSLContext

/** Certificates generated by the test JDK, with dates relative to the test run. */
internal class TlsTestMaterial {
    private val directory = Files.createTempDirectory("relay-tls-")
    private val password = "test-password"
    val ca: String
    val otherCa: String

    init {
        keytool("-genkeypair", "-alias", "self-signed", "-keystore", "self-signed.p12", "-dname", "CN=localhost",
            "-keyalg", "RSA", "-keysize", "2048", "-validity", "10", "-ext", "san=dns:localhost")
        createAuthority("ca")
        createAuthority("other-ca")
        ca = export("ca", "ca")
        otherCa = export("other-ca", "other-ca")
        createServer("server", "ca", "localhost")
        createServer("ip-server", "ca", "localhost", alternativeNames = "dns:localhost,ip:127.0.0.1")
        createServer("rotated", "ca", "localhost")
        createServer("other", "other-ca", "localhost")
        createServer("wrong-host", "ca", "other.example.test")
        createServer("expired", "ca", "localhost", "-2d", "1")
    }

    fun certificate(name: String): X509Certificate {
        return store(name).getCertificate(name) as X509Certificate
    }

    fun context(name: String): SSLContext {
        val keys = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm())
        keys.init(store(name), password.toCharArray())
        return SSLContext.getInstance("TLS").apply { init(keys.keyManagers, null, null) }
    }

    fun close() {
        directory.toFile().deleteRecursively()
    }

    private fun store(name: String): KeyStore {
        return KeyStore.getInstance("PKCS12").apply {
            Files.newInputStream(directory.resolve("$name.p12")).use { load(it, password.toCharArray()) }
        }
    }

    private fun createAuthority(name: String) {
        keytool("-genkeypair", "-alias", name, "-keystore", "$name.p12", "-dname", "CN=$name",
            "-keyalg", "RSA", "-keysize", "2048", "-validity", "30", "-ext", "bc:c=ca:true", "-ext", "ku=keyCertSign,cRLSign")
    }

    private fun export(store: String, alias: String): String {
        keytool("-exportcert", "-rfc", "-keystore", "$store.p12", "-alias", alias, "-file", "$alias.pem")
        return Files.readString(directory.resolve("$alias.pem"))
    }

    private fun createServer(name: String, issuer: String, host: String, start: String = "-1d", days: String = "10", alternativeNames: String = "dns:$host") {
        keytool("-genkeypair", "-alias", name, "-keystore", "$name.p12", "-dname", "CN=$host", "-keyalg", "RSA", "-keysize", "2048")
        keytool("-certreq", "-alias", name, "-keystore", "$name.p12", "-file", "$name.csr")
        keytool("-gencert", "-alias", issuer, "-keystore", "$issuer.p12", "-infile", "$name.csr", "-outfile", "$name.pem", "-rfc",
            "-startdate", start, "-validity", days, "-ext", "bc=ca:false", "-ext", "ku=digitalSignature,keyEncipherment",
            "-ext", "eku=serverAuth", "-ext", "san=$alternativeNames")
        keytool("-importcert", "-alias", issuer, "-keystore", "$name.p12", "-file", "$issuer.pem", "-noprompt")
        keytool("-importcert", "-alias", name, "-keystore", "$name.p12", "-file", "$name.pem", "-noprompt")
    }

    private fun keytool(vararg arguments: String) {
        val executable = Path.of(System.getProperty("java.home"), "bin", "keytool").toString()
        val process = ProcessBuilder(listOf(executable) + arguments + listOf("-storepass", password))
            .directory(directory.toFile()).redirectErrorStream(true).start()
        val output = process.inputStream.bufferedReader().readText()
        check(process.waitFor() == 0) { output }
    }
}
